# Generated by Django 4.2.18 on 2025-09-22 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('favicon', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('published', models.IntegerField(null=True)),
                ('cover', models.CharField(max_length=1000, null=True)),
                ('vector', models.TextField(null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feed')),
                ('keyword', models.ManyToManyField(default=dict, to='app.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('archive', 'Archive'), ('follow', 'Follow')], default='view', max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
                ('star', models.IntegerField(blank=True, default=0, null=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_article', to='app.article')),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_feed', to='app.feed')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_keyword', to='app.keyword')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'type'], name='app_interac_user_id_6913d1_idx'), models.Index(fields=['article'], name='app_interac_article_175b47_idx')],
            },
        ),
    ]
