# Generated by Django 4.2.18 on 2025-09-22 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False),
        ),
    ]
