# Generated by Django 4.2.18 on 2025-09-22 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_feed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='vector',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='vector',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
