# Generated by Django 4.2.18 on 2025-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feed_vector_keyword_vector_alter_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
