# Generated by Django 5.2.6 on 2025-09-25 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_article_vector_alter_feed_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='star',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('view', 'View'), ('read', 'Read'), ('like', 'Like'), ('comment', 'Comment'), ('archive', 'Archive'), ('follow', 'Follow')], default='view', max_length=20),
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed')},
            },
        ),
    ]
