# Generated by Django 5.0.6 on 2025-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_interaction_star_alter_interaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
