# Generated by Django 5.0.6 on 2025-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_article_abstract_alter_article_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["title", "abstract"], name="app_article_title_8c678e_idx"
            ),
        ),
    ]
