# Generated by Django 5.0.6 on 2025-10-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keywordtable",
            name="ForUser",
        ),
        migrations.AddField(
            model_name="keywordtable",
            name="agency",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyword_table",
                to="news_api.agencykey",
            ),
        ),
    ]
