# Generated by Django 5.0.6 on 2025-10-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0002_remove_keywordtable_foruser_keywordtable_agency"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanKeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="keywordtable",
            name="agency",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyword_table",
                to="news_api.agencykey",
            ),
        ),
        migrations.AlterField(
            model_name="searchkeyword",
            name="text",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="keywordtable",
            name="ban_words",
            field=models.ManyToManyField(to="news_api.bankeyword"),
        ),
    ]
