# Generated by Django 5.0.6 on 2025-10-15 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_article_abstract_alter_article_title_and_more"),
        ("news_api", "0003_bankeyword_alter_keywordtable_agency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleKeywordTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.article"
                    ),
                ),
                (
                    "keyword_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news_api.keywordtable",
                    ),
                ),
            ],
            options={
                "unique_together": {("article", "keyword_table")},
            },
        ),
    ]
