# Generated by Django 5.1 on 2025-01-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0015_news_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsagency',
            name='persian',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
