# Generated by Django 5.1 on 2025-01-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_alter_api_token_alter_iframe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='vector',
            field=models.TextField(null=True),
        ),
    ]
